# This workflow sets up and runs MSBuild
# to build and test a Visual Studio solution.

name: Build and Test

on: [push, pull_request]

jobs:

  run-msbuild:
    runs-on: windows-latest
    name: Run MSBuild and Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.1.0
        id: checkout_code
        
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1
        id: setup_msbuild
        
      - name: Run build_run
        id: run_msbuild
        working-directory: ${{ github.workspace }}
        run: build_run.bat
